Add serialization impls for `bool`
thunderbird/xml_struct pull request #4
Opened 2024-04-23 17:26 UTC by leftmostcat

Add default implementations for serializing boolean values.

2024-04-23 19:21 UTC, babolivier requested changes
Please add a test

2024-04-24 10:48 UTC, babolivier commented on xml_struct_tests/integration/core.rs
> +fn r#bool() {
question: Shouldn't this test live in https://github.com/thunderbird/xml-struct-rs/blob/main/xml_struct/src/tests.rs ? It looks to me like other similar tests are there (int, string).

2024-04-24 15:47 UTC, leftmostcat commented on xml_struct_tests/integration/core.rs
> +fn r#bool() {
Thanks for the suggestion. I forgot I had tests there.

2024-04-25 09:13 UTC, babolivier commented on xml_struct/src/tests.rs
> +    let expected = vec![(attr_name, "true").into()];
suggestion: it's not obvious from reading the code what the target type of `into()` is.

```suggestion
    let expected: Vec<Attribute> = vec![(attr_name, "true").into()];
```

2024-04-25 09:13 UTC, babolivier commented on xml_struct/src/tests.rs
> +fn bool() {
suggestion: for both coverage and consistency, there maybe should be a `bool_as_element` test similar to `int_as_element`.

2024-04-25 09:13 UTC, babolivier commented on xml_struct/src/tests.rs
> +    // Test `true` as an attribute value.
nitpick: for both consistency and atomicity I think it might be worth having the attribute tests in a separate function. wdyt?

2024-04-25 17:03 UTC, babolivier approved these changes

2024-04-25 17:06 UTC, merged